### ISSUE TITLE
Fetch packages from zap repo

### ISSUE THREAD

**Issue by oneingan** [ptribble/mvi#1]
Hi, why not fetch packages on-demand from zap repositories if it's not located in local cache? I can try to implement this but I'm not sure if exists any problem with that behavior?

**Comment by ptribble** [comment]
That's a good idea.

Currently, mvi doesn't really know where to get packages from, and the paths are hard coded. (Worse, they are the places on my personal build machine.) It has no notion of repositories, or catalogs, and cannot work out for itself what version of a package to install.

Requirements as notes for myself:

Should be aligned with the install.pkgs script in tribblix-build (which should also support retrieval of missing packages from a repo)

Should allow a Tribblix version different to that installed (or even to run on a non-Tribblix system); this is similar to the upgrade script

Should merge the package installer in mvi.sh and mvix.sh

In general, there are 3 possible modes for installing packages:
1. From the disk, as at present
2. From an explicit repo (like the upgrader)
3. Just like the current system (just "zap install -R /alt/root pkg_name")

**Comment by oneingan** [comment]
OK, maybe I can give you some help in that direction. Thanks.
