### ISSUE TITLE
/usr/sbin/rpcbind don't work

### ISSUE THREAD

**Issue by oneingan** [ptribble/mvi#2]
Hi, I'm trying to run rpcbind daemon in MVI but command is crashing. Maybe because /dev/tcp, /dev/udp, /dev/ticlts... have incorrect perms (0600). Seems like system is ignoring /etc/minor_perm definitions.

Regards.

**Comment by ptribble** [comment]
I think that's what is missing here is the following snippet from /lib/svc/method/fs-root:

```
> #
> # Update kernel driver.conf cache with any additional driver.conf
> # files found on /usr, and device permissions from /etc/minor_perm.
> #
> /usr/sbin/devfsadm -I -P
> 
```

So, if you invoke devfsadm like that, it should fix it. (Both the apparent permissions as shown by ls, and the underlying kernel permissions.) Does that work?

**Comment by oneingan** [comment]
Yes, it works. I catch well now how works underlying svc methods. I'll double check the next one. Thanks for all.
